parameters:
    database_driver: pdo_mysql
    database_host: 127.0.0.1
    database_port: 3306
    database_name: sf
    database_user: root
    database_password: '12345'
    mailer_transport: smtp
    mailer_host: 127.0.0.1
    mailer_user: null
    mailer_password: null
    locale: en
    secret: 8c9e24a155bb1389899e39f3ed0c8e946d9a8ea4
    database_path: null
