parameters:
#    dwpubcoffee_maker.example.class: dwpub\coffeeMakerBundle\Example

services:
#    dwpubcoffee_maker.example:
#        class: %dwpubcoffee_maker.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
