<?php

namespace dwpub\coffeeMakerBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * CoffeeBeanRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CoffeeBeanRepository extends EntityRepository
{
}
